version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8448:8448"
    depends_on:
      - mongo
      - languagetool
    environment:
      - MONGO_URI=mongodb://mongo:27017/kolderdb
      - PORT=8448

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  languagetool:
    image: erikvl87/languagetool
    ports:
      - "8010:8010"
    restart: always

volumes:
  mongo-data: